name: Android CI from ZIP (APK Artifact)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Unzip and detect project
        run: |
          set -euxo pipefail
          ZIP_FILE="$(ls -1 *.zip | head -n1)"
          test -n "$ZIP_FILE"
          mkdir -p src
          unzip -q "$ZIP_FILE" -d src
          ROOT="$(find src -type f -name gradlew -print -quit)"
          test -n "$ROOT"
          PRJDIR="$(dirname "$ROOT")"
          echo "PRJDIR=$PRJDIR" >> $GITHUB_ENV
          # line-endings safeguard
          sed -i 's/\r$//' "$ROOT"
          chmod +x "$ROOT"

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Debug APK
        run: |
          "${PRJDIR}/gradlew" -p "${PRJDIR}" :app:assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: truth-or-dare-debug-apk
          path: ${{ env.PRJDIR }}/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
